### ISSUE TITLE
Timestamp from upstream database packages

### ISSUE THREAD

**Issue by uboslinux** [uboslinux/macrobuild-ubos#8]
I think this is what is happening:

1. Upstream updates a database, e.g. extra.db
2. After some time, the mirror we use gets the the updated database, using the timestamp on the file of the original update
3. When we download the database file, we timestamp it with the time of download
4. When we look for updates, we (well, curl -z) compare the local timestamp (the time of download) against the time of update, and skip re-downloading if there hasn't been a more recent upstream change.
5. If we happen to download during the time window between step 1 and step 2 above, we miss an update

Solution: find a way to set the timestamp of the downloaded file to the same as the upstream database file, not the time of download.

**Comment by indiebox** [comment]
Seems curl has a -R (--remote-time) flag, which should do what we want. 398740b375c85807eea9b876db484762db44ce74 should fix this, but let's put it on probation.

**Comment by jernst** [comment]
Seems to work now.
